name: watashi_locale
description: A localization utility that supports multi-level dictionary merging, custom score-based locale matching and more.
version: 0.0.2
repository: https://github.com/oniyukai/watashi_locale.git

environment:
  sdk: ">=3.10.8 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ">=1.17.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
